#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0-or-later

#    ----------------------------------------------------------------------
#    Copyright © 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="$( \
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_libevm="${_lib}/libevm/libevm"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"
_sourced \
  "${_libevm}"

# shellcheck disable=SC2034
_global_variables() {
  call_date=""
  ur_address=""
  ur_version=""
  up_address=""
  up_version=""
  pp_address=""
  pp_version=""
  cache_dir=""
  gnupg_home=""
  gnupg_private=""
  source_publisher=""
  measure_unit=""
  target_package=""
  target_revision=""
  info_type=""
  update_force=""
  command_args=()
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'libevm-requirements' \
    'libevm'
  libevm-requirements
  _check_cmd \
    'evm-contract-call' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-contract-deployment-networks' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-wallet'
}

_conf_dir_auto_detect() {
  local \
    _dir
  _dir="${HOME}/.config/ur/packages"
  echo \
    "${_dir}"
}

_cache_dir_auto_detect() {
  local \
    _dir
  _dir="${HOME}/.cache/ur/packages"
  echo \
    "${_dir}"
}

_contract_call_opts_setup() {
  local \
    _abi="${1}" \
    _bytecode="${2}" \
    _compiler_output="${3}"
  _contract_call_opts+=(
    -n
      "${_target_network}"
    -N
      "${_wallet_name}"
    -k
      "${_api_key_path}"
    -A
      "${_abi}"
    -B
      "${_bytecode}"
    -C
      "${_compiler_output}"
  )
}

_publishers_call_opts_setup() {
  local \
    _contract_call_opts=()
  _contract_call_opts_setup \
    "${_pp_abi}" \
    "${_pp_bytecode}" \
    "${_pp_compiler_output}"
  _publishers_call_opts+=(
    "${_contract_call_opts[@]}"
    -t
      "static"
  )
}

_revisions_call_opts_setup() {
  local \
    _contract_call_opts=()
  _contract_call_opts_setup \
    "${_ur_abi}" \
    "${_ur_bytecode}" \
    "${_ur_compiler_output}"
  _revisions_call_opts+=(
    "${_contract_call_opts[@]}"
    -t
      "static"
  )
}

_prices_call_opts_setup() {
  local \
    _contract_call_opts=()
  _contract_call_opts_setup \
    "${_ur_abi}" \
    "${_ur_bytecode}" \
    "${_ur_compiler_output}"
  _prices_call_opts+=(
    "${_contract_call_opts[@]}"
    -t
      "static"
  )
}

_package_publishers_get() {
  local \
    _pp_address="${1}" \
    _pp_version="${2}" \
    _ur_address="${3}" \
    _up_address="${4}" \
    _package="${5}" \
    _msg=() \
    _pp_abi \
    _pp_bytecode \
    _pp_compiler_output \
    _publisher \
    _publishers_total
  _contract_artifacts_auto_detect \
    "${_deployments_dir}" \
    "${_target_network}" \
    "PackagePublishers" \
    "_pp" \
    "${_pp_version}"
  _publishers_call_opts_setup 
  _publishers_total="$( \
    evm-contract-call \
      "${_publishers_call_opts[@]}" \
      "${_pp_address}" \
      "packagePublisherNo" \
      "${_ur_address}" \
      "${_up_address}" \
      "${_package}")"
  for _publisher \
    in $(seq 1 \
             "${_publishers_total}"); do
    _publishers+=( "$( \
       evm-contract-call \
        "${_publishers_call_opts[@]}" \
        "${_pp_address}" \
        "packagePublisher" \
        "${_ur_address}" \
        "${_up_address}" \
        "${_package}" \
        "${_publisher}")"
    )
  done
  if (( "${#_publishers[@]}" == 0 )); then
    _msg=(
      "No registered publishers"
      "for package '${_package}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  else
    _msg=(
      "Publishers for '${_package}':"
      "${_publishers[@]}."
    )
    _msg_info \
      "${_msg[*]}"
  fi
  printf \
    "%s\n" \
    "${_publishers[@]}"
}

_package_revisions_get() {
  local \
    _package="${1}" \
    _target_publisher="${2}" \
    _publishers_total \
    _revisions_call_opts=() \
    _ur_abi \
    _ur_bytecode \
    _ur_compiler_output
  _contract_artifacts_auto_detect \
    "${_deployments_dir}" \
    "${_target_network}" \
    "UserRepository" \
    "_ur" \
    "${_ur_version}"
  _revisions_call_opts_setup 
  _revisions_total="$(
    evm-contract-call \
      "${_revisions_call_opts[@]}" \
      "${_ur_address}" \
      "revNo" \
      "${_package}" \
      "${_target_publisher}")"
}

_revision_dir_get() {
  echo \
    "${_cache_dir}/packages/${_target_publisher}/${_package}/${_revision}"
}

_revision_price_save(){
  local \
    _package="${1}" \
    _target_publisher="${2}" \
    _revision="${3}" \
    _price="${4}" \
    _dest_dir
  _dest_dir="$(
    _revision_dir_get)"
  echo "${_dest_dir}"
  mkdir \
    -p \
    "${_dest_dir}"
  echo \
    "${_price}" > \
    "${_dest_dir}/price"
}

_revision_price_local_get() {
  local \
    _package="${1}" \
    _target_publisher="${2}" \
    _revision="${3}" \
    _revision_dir
  _revision_dir="$(
    _revision_dir_get)"
  cat \
    "${_revision_dir}/price"
}

_revision_price_get() {
  local \
    _package="${1}" \
    _target_publisher="${2}" \
    _msg=() \
    _revision \
    _revisions=() \
    _prices_call_opts=() \
    _price \
    _ur_abi \
    _ur_bytecode \
    _ur_compiler_output \
    _update
  shift \
    2
  _revisions+=(
    "$@"
  )
  _update="${_update_force}"
  for _revision in "${_revisions[@]}"; do
    _revision_dir="$(
      _revision_dir_get)"
    if [[ ! -e "${_revision_dir}/price" ]]; then
      _update="y"
      _contract_artifacts_auto_detect \
        "${_deployments_dir}" \
        "${_target_network}" \
        "UserRepository" \
        "_ur" \
        "${_ur_version}"
      _prices_call_opts_setup 
      break
    fi
  done
  for _revision in "${_revisions[@]}"; do
    if [[ "${_update}" == "y" ]]; then
      _msg=(
        "Getting price for revision"
        "'${_revision}'."
      )
      _msg_info \
        "${_msg[*]}"
      _price="$(
        evm-contract-call \
          "${_prices_call_opts[@]}" \
          "${_ur_address}" \
          "price" \
          "${_package}" \
          "${_target_publisher}" \
          "${_revision}")"
      if [[ "${_price}" != "" ]]; then
        _revision_price_save \
          "${_package}" \
          "${_target_publisher}" \
          "${_revision}" \
          "${_price}"
      fi
    else
      echo "ciao"
      _price="$(
        _revision_price_local_get \
          "${_package}" \
          "${_target_publisher}" \
          "${_revision}")"
    fi
    if [[ "${_measure_unit}" == "ether" ]]; then
      _price="$(
        echo \
          "scale=18;${_price} / 1000000000000000000" | \
          bc)"
    fi
    _prices+=(
      "${_price}"
    )
  done
  printf \
    "%s\n" \
    "${_prices[@]}"
}

_ur_package_info() {
  local \
    _ur_address="${1}" \
    _ur_version="${2}" \
    _up_address="${3}" \
    _up_version="${4}" \
    _pp_address="${5}" \
    _pp_version="${6}" \
    _deployments_dir="${7}" \
    _wallet_name="${8}" \
    _wallet_path="${9}" \
    _wallet_password="${10}" \
    _wallet_seed="${11}" \
    _target_network="${12}" \
    _api_key_path="${13}" \
    _cache_dir="${14}" \
    _gnupg_home="${15}" \
    _gnupg_private="${16}" \
    _source_publisher="${17}" \
    _target_package="${18}" \
    _target_revision="${19}" \
    _info_type="${20}" \
    _measure_unit="${21}" \
    _update_force="${22}" \
    _ur_publishers_opts=() \
    _command_args=() \
    _cmd \
    _args=() \
    _msg=() \
    _publishers=() \
    _revisions_total \
    _revisions=() \
    _prices=()
  shift \
    22
  _command_args+=(
    "$@"
  )
  if [[ "${_source_publisher}" == "" ]]; then
    _msg=(
      "Source publisher not selected,"
      "showing all available."
    )
    _msg_warning \
      "${_msg[*]}"
    _info_type="publishers"
  fi
  if [[ "${_info_type}" == "publishers" ]]; then
    _package_publishers_get \
      "${_pp_address}" \
      "${_pp_version}" \
      "${_ur_address}" \
      "${_up_address}" \
      "${_target_package}"
  fi
  if [[ "${_info_type}" == "revisions" ]]; then
    _package_revisions_get \
      "${_target_package}" \
      "${_source_publisher}"
    echo \
      "${_revisions_total}"
  fi
  if [[ "${_info_type}" == "prices" ]]; then
    _package_revisions_get \
      "${_target_package}" \
      "${_source_publisher}"
    if [[ "${_target_revision}" == "" ]]; then
      _msg=(
        "Target revision not selected,"
        "showing prices for all available"
        "'${_revisions_total}' revisions."
      )
      _msg_warning \
        "${_msg[*]}"
      _revisions=( $(
        seq \
          "0" \
          "$(("${_revisions_total}" - 1))")
      )
    elif [[ "${_target_revision}" == "latest" ]]; then
      _revisions=(
        "${_revisions_total}"
      )
    else
      _revisions=(
        "${_target_revision}"
      )
    fi
    _revision_price_get \
      "${_target_package}" \
      "${_source_publisher}" \
      "${_revisions[@]}"
  fi
}

_set_overrides() {
  local \
    _call_auth
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "call" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "user" \
    "level" \
    "n"
  _deployments_dir_auto_detect \
    "ur" \
    "${user_level}"
  _network_auto_detect \
    "UserRepository" \
    "${deployments_dir}" \
    "${user_level}"
  _api_key_auto_detect \
    "${target_network}"
  _set_override \
    "wallet" \
    "name" \
    "default"
  _call_auth="y"
  if [[ "${target_package}" == "" ]]; then
    _call_auth="n"
  fi
  _wallet_overrides_set \
    "evm-wallet" \
    "${wallet_name}" \
    "${_call_auth}"
  _set_override \
    "cache" \
    "dir" \
    "$(_cache_dir_auto_detect)"
  _set_override \
    "gnupg" \
    "home" \
    "${cache_dir}/gnupg"
  _set_override \
    "gnupg" \
    "private" \
    "$(_conf_dir_auto_detect)/gnupg"
  _contract_setup_auto_detect \
    "ur" \
    "UserRepository" \
    "ur" \
    "${target_network}" \
    "${user_level}" \
    "${deployments_dir}"
  _contract_setup_auto_detect \
    "ur" \
    "UserRepositoryPublishers" \
    "up" \
    "${target_network}" \
    "${user_level}" \
    "${deployments_dir}"
  _contract_setup_auto_detect \
    "ur" \
    "PackagePublishers" \
    "pp" \
    "${target_network}" \
    "${user_level}" \
    "${deployments_dir}"
  _set_override \
    "source" \
    "publisher" \
    ""
  _set_override \
    "target" \
    "package" \
    ""
  _set_override \
    "target" \
    "revision" \
    "latest"
  _set_override \
    "info" \
    "type" \
    "publishers"
  _set_override \
    "measure" \
    "unit" \
    "ether"
  _set_override \
    "update" \
    "force" \
    "n"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _up \
    _up_deployment \
    _networks \
    _usage_text
  _ur="UserRepository"
  _ur_deployment="${deployments_dir}/${_ur}"
  _networks=( $( \
    evm-contract-deployment-networks \
      -A \
      "${_ur_deployment}")
  )
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Retrieves information about Ur packages.

Usage:
  ${app_name}
    [options]
    <package>

  networks:
$(_display_networks \
     "${_networks[@]}")

  options:
     -P <publisher>         Target package publisher.
                            Default: ${source_publisher}
     -r <revision>          Target package revision.
                            Default: ${target_revision}
     -i <info_type>         It can be 'publishers',
                            'revisions', 'prices'.
                            Default: ${info_type}
     -y                     Forces retrieving the information
                            from the network rather than locally.
                            Default: ${update_force}

  display options:
     -m <measure-unit>      Measure unit for the network
                            currency. It can be 'ether'
                            and 'wei'.
                            Default: ${measure_unit}

  contract options:
     -A <ur_address>        Address of the 'User Repository'
                            contract on the
                            network.
                            Default: ${ur_address}
     -V <ur_version>        Version of the target 'User Repository'
                            contract on the network.
                            Default: ${ur_version}
     -B <up_address>        Address of the 'User Repository
                            Publishers' contract on the
                            network.
                            Default: ${up_address}
     -C <pp_address>        Address of the 'Package
                            Publishers' contract on the
                            network.
                            Default: ${pp_address}
  network options:
     -u                     Whether to retrieve publishers' contract
                            address from user directory or custom
                            deployment.
                            Default: ${user_level}
     -d <deployments_dir>   Contracts deployments directory.
                            Default: ${deployments_dir}

  credentials options:
     -N <wallet_name>       Wallet name.
                            Default: ${wallet_name}
     -w <wallet_path>       Wallet path.
                            Default: ${wallet_path}
     -p <wallet_password>   Wallet password.
                            Default: ${wallet_password}
     -s <wallet_seed>       Wallet seed path.
                            Default: ${wallet_seed}
     -n <network>           EVM network name (${_networks[*]}).
                            Default: ${target_network}
     -k <api_key>           Etherscan-like service key.
                            Default: ${api_key}

  app options:
     -W <cache_dir>         Work directory.
                            Default: ${cache_dir}
     -H <gnupg_home>        GNUPG home directory.
                            Default: ${gnupg_home}
     -G <gnupg_private>     GNUPG private home directory.
                            Default: ${gnupg_private}

     -h                     This message.
     -c                     Enable color output
     -v                     Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flag \
    _flags=(
      "${1}"
    )
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                      Call date:   ${call_date}"
  _msg_info "                 Target package:   ${target_package}"
  _msg_info "               Source publisher:   ${source_publisher}"
  _msg_info "                Target revision:   ${target_revision}"
  _msg_info "                      Info type:   ${info_type}"
  _msg_info "              Force info update:   ${update_force}"
  _msg_info "              Display options:"
  _msg_info "                   Measure unit:   ${measure_unit}"
  _msg_info "             Contract options:"
  _msg_info "             Repository address:   ${ur_address}"
  _msg_info "             Repository version:   ${ur_version}"
  _msg_info "             Publishers address:   ${up_address}"
  _msg_info "              Packagers address:   ${pp_address}"
  _msg_info "   LibEVM application options:"
  _msg_info "                     User level:   ${user_level}"
  _msg_info "          Deployments directory:   ${deployments_dir}"
  _msg_info "                Target networks:   ${target_networks[*]}"
  _msg_info "          Credentials options:"
  _msg_info "                    Wallet name:   ${wallet_name}"
  _msg_info "                 Wallet address:   ${wallet_address}"
  _msg_info "                    Wallet path:   ${wallet_path}"
  _msg_info "                Wallet password:   ${wallet_password}"
  _msg_info "                    Wallet seed:   ${wallet_seed}"
  _msg_info "                        API key:   ${api_key}"
  _msg_info "          Application options:"
  _msg_info "                Cache directory:   ${cache_dir}"
  _msg_info "                GNUPG directory:   ${gnupg_home}"
  _msg_info "        GNUPG private directory:   ${gnupg_private}"
}

_globals
_global_variables
_libevm_global_variables
_libevm_app_global_variables
_requirements
# shellcheck disable=SC2034
getopts_opts="$( \
  printf \
    "%s" \
    "P:r:i:y" \
    "A:V:" \
    "$(_libevm_app_getopts_params_get)" \
    "n:" \
    "$(_wallet_getopts_params_get)" \
    "G:H:W:cvh")"
while \
  getopts \
    "${getopts_opts}" \
    arg; do
  _wallet_getopts_case
  _libevm_app_getopts_case
  case \
    "${arg}" in
    P)
      override_source_publisher="${OPTARG}" ;;
    r)
      override_target_revision="${OPTARG}" ;;
    i)
      override_info_type="${OPTARG}" ;;
    y)
      override_update_force="y" ;;
    A)
      override_up_address="${OPTARG}" ;;
    V)
      override_up_version="${OPTARG}" ;;
    n)
      override_target_network="${OPTARG}" ;;
    W)
      override_cache_dir="${OPTARG}" ;;
    H)
      override_gnupg_home="${OPTARG}" ;;
    G)
      override_gnupg_private="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg_error \
        "Invalid argument '${arg}'" \
        0
      _usage \
        1 ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _msg=(
    "No package specified."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _set_overrides
  _usage \
    1
fi
if (( 0 < $# )); then
  target_package="${1}"
fi
shift \
  1 || \
  true
command_args+=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${ur_address}"
  "${ur_version}"
  "${up_address}"
  "${up_version}"
  "${pp_address}"
  "${pp_version}"
  "${deployments_dir}"
  "${wallet_name}"
  "${wallet_path}"
  "${wallet_password}"
  "${wallet_seed}"
  "${target_network}"
  "${api_key}"
  "${cache_dir}"
  "${gnupg_home}"
  "${gnupg_private}"
  "${source_publisher}"
  "${target_package}"
  "${target_revision}"
  "${info_type}"
  "${measure_unit}"
  "${update_force}"
)
_ur_package_info \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
