#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"
source \
  "${_lib}/libevm/libevm"

# shellcheck disable=SC2034
_global_variables() {
  call_date=""
  ur_address=""
  ur_version=""
  up_address=""
  up_version=""
  pp_address=""
  pp_version=""
  deployments_dir=""
  user_level=""
  wallet_name=""
  wallet_path=""
  wallet_password=""
  wallet_seed=""
  wallet_address=""
  target_network=""
  api_key=""
  cache_dir=""
  gnupg_home=""
  gnupg_private=""
  source_publisher=""
  target_package=""
  target_revision=""
  command_args=()
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'libevm-requirements' \
    'libevm'
  libevm-requirements
  _check_cmd \
    'evm-contract-call' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-contract-deployment-networks' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-wallet'
  _check_cmd \
    "ur-publishers" \
    "ur"
}

_conf_dir_auto_detect() {
  local \
    _dir
  _dir="${HOME}/.config/ur/packages"
  echo \
    "${_dir}"
}

_cache_dir_auto_detect() {
  local \
    _dir
  _dir="${HOME}/.cache/ur/packages"
  echo \
    "${_dir}"
}

_contract_call_opts_setup() {
  local \
    _abi="${1}" \
    _bytecode="${2}" \
    _compiler_output="${3}"
  _contract_call_opts+=(
    -n
      "${_target_network}"
    -N
      "${_wallet_name}"
    -k
      "${_api_key_path}"
    -A
      "${_abi}"
    -B
      "${_bytecode}"
    -C
      "${_compiler_output}"
  )
}

_providers_call_opts_setup() {
  local \
    _contract_call_opts=()
  _contract_call_opts_setup \
    "${_pp_abi}" \
    "${_pp_bytecode}" \
    "${_pp_compiler_output}"
  _providers_call_opts+=(
    "${_contract_call_opts[@]}"
    -t
      "static"
  )
}

_publisher_list_call_opts_setup() {
  local \
    _contract_call_opts=()
  _contract_call_opts_setup
  _publish_call_opts+=(
    "${_contract_call_opts[@]}"
    -t
      "dynamic"
  )
  _check_call_opts+=(
    "${_contract_call_opts[@]}"
    -t
      "static"
  )
}



_work_dir_setup() {
  local \
    _msg=()
  _tmp_dir="${_cache_dir}"
  _msg=(
    "setting up work directory"
    "'${_tmp_dir}'"
  )
  _msg_info \
    "${_msg[*]}"
  mkdir \
    -p \
    "${_tmp_dir}/gnupg"
  chmod \
    -R \
    700 \
    "${_tmp_dir}"
}

_publishers_new_get() {
  local \
    _publisher \
    _bound_lower \
    _bound_upper \
    _publishers_remote_total \
    _publishers_local_total \
    _publishers_new \
    _msg=()
  _publishers_remote_total="$(( \
    "$(evm-contract-call \
        "${_list_call_opts[@]}" \
        "${_up_address}" \
        "publisherNo")" - 1))"
  _msg=(
    "a total of '${_publishers_remote_total}'"
    "are listed on the repository."
  )
  _msg_info \
    "${_msg[*]}"
  _publishers_local_total="$( \
    wc \
      -l \
      "${_publishers_db}" | \
      awk \
        '{print $1}')" 
  _msg=(
    "locally are listed"
    "'${_publishers_local_total}'"
    "publishers."
  )
  _msg_info \
    "${_msg[*]}"
  _publishers_new="$(( \
   _publishers_remote_total - \
   _publishers_local_total))"
  if (( 0 < "${_publishers_new}" )); then
    _msg=(
      "getting info for new"
      "'${_publishers_new}' publishers"
    )
    _msg_info \
      "${_msg[*]}"
    _bound_lower="$(( \
      _publishers_local_total \
      + 1))"
    _bound_upper="$(( \
      _publishers_remote_total))"
    for _publisher \
      in $(seq "${_bound_lower}" \
               "${_bound_upper}"); do
      _msg=(
        "retrieving publisher '${_publisher}'"
        "out of '${_bound_upper}'"
      )
      _msg_info \
        "${_msg[*]}"
      printf \
        '%s\n' \
        "$(evm-contract-call \
             "${_list_call_opts[@]}" \
             "${_up_address}" \
             "publisher" \
             "${_publisher}")" >> \
        "${_publishers_db}"
    done
  fi
}

_publishers_info_get() {
  local \
    _publisher \
    _publishers=() \
    _evm_openpgp_key_receive_opts=()
  if [[ "${quiet}" == "n" ]]; then
    _evm_openpgp_key_receive_opts+=(
      -v
    )
  fi
  _evm_openpgp_key_receive_opts+=(
    -H
      "${_gnupg_home}"
  )
  _publishers+=(
    $(cat \
        "${_publishers_db}")
  )
  for _publisher in "${_publishers[@]}"; do
    _msg=(
      "retrieving information for"
      "publisher '${_publisher}'"
    )
    _msg_info \
      "${_msg[*]}"
    evm-openpgp-key-receive \
      "${_evm_openpgp_key_receive_opts[@]}" \
      "${_publisher}"
  done
}

_publishers_update() {
  local \
    _target_network="${1}" \
    _up_address="${2}" \
    _abi="${3}" \
    _bytecode="${4}" \
    _compiler_output="${5}" \
    _work_dir="${6}" \
    _gnupg_home="${7}" \
    _msg=() \
    _publishers_db \
    _tmp_dir \
    _list_call_opts=() \
    _info_call_opts=()
  _publishers_update_call_opts_setup
  _msg=(
    "updating publishers"
  )
  _msg_info \
    "${_msg[*]}"
  _work_dir_setup
  _publishers_db="${_work_dir}/publishers.db"
  if [[ ! -e "${_publishers_db}" ]]; then
    touch \
      "${_publishers_db}"
    chmod \
      600 \
      "${_publishers_db}"
  fi
  _publishers_new_get
  _publishers_info_get
}

_publishers_list() {
  local \
    _gnupg_home="${1}" \
    _gpg_opts=() \
    _msg=()
  _msg=(
    "listing publishers"
  )
  _msg_info \
    "${_msg[*]}"
  _gpg_opts+=(
    --homedir
      "${_gnupg_home}"
    --list-keys
  )
  GNUPG_HOME="${_gnupg_home}" \
  gpg \
    "${_gpg_opts[@]}"
}

_keys_private_check() {
  local \
    _user_name="${1}" \
    _gpg_opts=() \
    _subkey_encryption \
    _msg=()
  if [[ "${_user_name}" == "" ]]; then
    _user_name="*"
  fi
  _keys_private="n"
  _gpg_opts=(
    --homedir
      "${_gnupg_private}"
    --list-secret-keys
    --with-colons
  )
  _subkey_encryption="$( \
    gpg \
      "${_gpg_opts[@]}" \
      "${_user_name}@${_target_address}" | \
      grep \
        "^ssb" | 
        head \
          -n \
            1 | \
          awk \
            -F \
              ":" \
              '{print $12}' || \
        true)"
  if [[ "${_subkey_encryption}" == "e" ]]; then
    _msg=(
      "found encryption-capable private subkeys"
      "for address '${_target_address}' in"
      "GNUPG home '${_gnupg_private}'."
    )
    _keys_private="y"
  elif [[ "${_subkey_encryption}" == "" ]]; then
    _msg=(
      "there are no encryption-capable"
      "private keys for address"
      "'${_target_address}' in GNUPG home"
      "'${_gnupg_private}'."
    )
    _msg_info \
      "${_msg[*]}"
  fi
}

_package_providers_get() {
  local \
    _pp_address="${1}" \
    _pp_version="${2}" \
    _ur_address="${3}" \
    _up_address="${4}" \
    _package="${5}" \
    _msg=() \
    _pp_abi \
    _pp_bytecode \
    _pp_compiler_output \
    _publisher \
    _publishers=() \
    _publishers_total
  _pp_abi="$( \
    _contract_abi_get \
      "${_deployments_dir}" \
      "${_target_network}" \
      "PackagePublishers" \
      "${_pp_version}")"
  _pp_bytecode="$( \
    _contract_bytecode_get \
      "${_deployments_dir}" \
      "${_target_network}" \
      "PackagePublishers" \
      "${_pp_version}")"
  _pp_compiler_output="$( \
    _contract_compiler_output_get \
      "${_deployments_dir}" \
      "${_target_network}" \
      "PackagePublishers" \
      "${_pp_version}")"
  _providers_call_opts_setup 
  _publishers_total="$( \
    evm-contract-call \
      "${_providers_call_opts[@]}" \
      "${_pp_address}" \
      "packagePublisherNo" \
      "${_ur_address}" \
      "${_up_address}" \
      "${_package}")"
  for _publisher \
    in $(seq 1 \
             "${_publishers_total}"); do
     evm-contract-call \
       -v \
      "${_providers_call_opts[@]}" \
      "${_pp_address}" \
      "packagePublisher" \
      "${_ur_address}" \
      "${_up_address}" \
      "${_package}" \
      "${_publisher}"
    _publishers+=( "$( \
       evm-contract-call \
        "${_providers_call_opts[@]}" \
        "${_pp_address}" \
        "packagePublisher" \
        "${_ur_address}" \
        "${_up_address}" \
        "${_package}" \
        "${_publisher}")"
    )
  done
  if (( "${#_publishers[@]}" == 0 )); then
    _msg=(
      "No registered publishers"
      "for package '${_package}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  else
    _msg=(
      "Publishers for '${_package}':"
      "${_publishers[@]}."
    )
    _msg_info \
      "${_msg[*]}"
  fi
}

_ur_package_info() {
  local \
    _ur_address="${1}" \
    _ur_version="${2}" \
    _up_address="${3}" \
    _up_version="${4}" \
    _pp_address="${5}" \
    _pp_version="${6}" \
    _deployments_dir="${7}" \
    _wallet_name="${8}" \
    _wallet_path="${9}" \
    _wallet_password="${10}" \
    _wallet_seed="${11}" \
    _target_network="${12}" \
    _api_key_path="${13}" \
    _cache_dir="${14}" \
    _gnupg_home="${15}" \
    _gnupg_private="${16}" \
    _source_publisher="${17}" \
    _target_package="${18}" \
    _target_revision="${19}" \
    _ur_publishers_opts=() \
    _command_args=() \
    _cmd \
    _args=() \
    _msg=()
  shift \
    19
  _command_args+=(
    "$@"
  )
  if [[ "${_source_publisher}" == "" ]]; then
    _msg=(
      "Source publisher not selected,"
      "showing info for all of the available"
      "ones."
    )
    _msg_info \
      "${_msg[*]}"
    _package_providers_get \
      "${_pp_address}" \
      "${_pp_version}" \
      "${_ur_address}" \
      "${_up_address}" \
      "${_target_package}"
    # if [[ "${quiet}" == "n" ]]; then
    #   _ur_publishers_opts+=(
    #     -v
    #   )
    # fi
    # ur-publishers \
    #   "${_ur_publishers_opts[@]}" \
    #   update
  fi
  # _publishers_info_get \
  #   "${_target_network}" \
  #   "${_pp_address}" \
  #   "${_pp_abi}" \
  #   "${_pp_bytecode}" \
  #   "${_pp_compiler_output}" \
  #   "${_cache_dir}" \
  #   "${_gnupg_home}"
}

_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "call" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "wallet" \
    "name" \
    "default"
  _set_override \
    "user" \
    "level" \
    "n"
  _deployments_dir_auto_detect \
    "ur" \
    "$(_get \
         "user" \
         "level")"
  _network_auto_detect \
    "UserRepository" \
    "$(_get \
         "deployments" \
         "dir")" \
    "$(_get \
         "user" \
         "level")"
  _api_key_auto_detect \
    "$(_get \
         "target" \
         "network")"
  _set_override \
    "wallet" \
    "path" \
    "$(_wallet_path_get \
         "evm-wallet" \
         "$(_get \
              "wallet" \
              "name")")"
  _secret_auto_detect \
    "seed" \
    "seed" \
    "evm-wallet" \
    "$(_get \
         "wallet" \
         "name")"
  _secret_auto_detect \
    "password" \
    "plain" \
    "evm-wallet" \
    "$(_get \
         "wallet" \
         "name")"
  _set_override \
    "wallet" \
    "address" \
    "$(evm-wallet \
         get \
           "$(_get \
                "wallet" \
                "name")" \
           "address")"
  _set_override \
    "cache" \
    "dir" \
    "$(_cache_dir_auto_detect)"
  _set_override \
    "gnupg" \
    "home" \
    "$(_get \
         "cache" \
         "dir")/gnupg"
  _set_override \
    "gnupg" \
    "private" \
    "$(_conf_dir_auto_detect)/gnupg"
  _contract_setup_auto_detect \
    "ur" \
    "UserRepository" \
    "ur" \
    "${target_network}" \
    "${user_level}" \
    "${deployments_dir}"
  _contract_setup_auto_detect \
    "ur" \
    "UserRepositoryPublishers" \
    "up" \
    "${target_network}" \
    "${user_level}" \
    "${deployments_dir}"
  _contract_setup_auto_detect \
    "ur" \
    "PackagePublishers" \
    "pp" \
    "${target_network}" \
    "${user_level}" \
    "${deployments_dir}"
  _set_override \
    "source" \
    "publisher" \
    ""
  _set_override \
    "target" \
    "package" \
    ""
  _set_override \
    "target" \
    "revision" \
    "latest"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _up \
    _up_deployment \
    _networks \
    _usage_text
  _ur="UserRepository"
  _ur_deployment="$( \
    _get \
      "deployments" \
      "dir")/${_ur}"
  _networks="$( \
    evm-contract-deployment-networks \
      -A \
      "${_ur_deployment}")"
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Retrieves information about Ur packages.

Usage:
  $(_get "app" "name")
    [options]
    <package>

  networks:
$(_display_networks \
     "${_networks[*]}")

  options:
     -A <ur_address>        Address of the 'User Repository'
                            contract on the
                            network.
                            Default: ${ur_address}
     -V <ur_version>        Version of the target 'User Repository'
                            contract on the network.
                            Default: ${ur_version}
     -B <up_address>        Address of the 'User Repository
                            Publishers' contract on the
                            network.
                            Default: ${up_address}
     -C <pp_address>        Address of the 'Package
                            Publishers' contract on the
                            network.
                            Default: ${pp_address}
     -u                     Whether to retrieve publishers' contract
                            address from user directory or custom
                            deployment.
                            Default: ${user_level}
     -d <deployments_dir>   Contracts deployments directory.
                            Default: $(_get "deployments" "dir")
     -N <wallet_name>       Wallet name.
                            Default: $(_get "wallet" "name")
     -w <wallet_path>       Wallet path.
                            Default: $(_get "wallet" "path")
     -p <wallet_password>   Wallet password.
                            Default: $(_get "wallet" "password")
     -s <wallet_seed>       Wallet seed path.
                            Default: $(_get "wallet" "seed")
     -n <network>           EVM network name (${_networks[*]}).
                            Default: $(_get "target" "network")
     -k <api_key>           Etherscan-like service key.
                            Default: $(_get "api" "key")
     -C <cache_dir>         Work directory.
                            Default: $(_get "cache" "dir")
     -H <gnupg_home>        GNUPG home directory.
                            Default: $(_get "gnupg" "home")
     -G <gnupg_private>     GNUPG private home directory.
                            Default: $(_get "gnupg" "private")
     -P <publisher>         Target package publisher.
                            Default: $(_get "source" "publisher")
     -r <revision>          Target package revision.
                            Default: $(_get "target" "revision")

     -h                     This message.
     -c                     Enable color output
     -v                     Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flag \
    _flags=(
      "${1}"
    )
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                Call date:   ${call_date}"
  _msg_info "       Repository address:   ${ur_address}"
  _msg_info "       Repository version:   ${ur_version}"
  _msg_info "       Publishers address:   ${up_address}"
  _msg_info "        Packagers address:   ${pp_address}"
  _msg_info "               User level:   ${user_level}"
  _msg_info "    Deployments directory:   ${deployments_dir}"
  _msg_info "           Wallet address:   ${wallet_address}"
  _msg_info "              Wallet name:   ${wallet_name}"
  _msg_info "              Wallet path:   ${wallet_path}"
  _msg_info "          Wallet password:   ${wallet_password}"
  _msg_info "              Wallet seed:   ${wallet_seed}"
  _msg_info "           Target network:   ${target_network}"
  _msg_info "                  API key:   ${api_key}"
  _msg_info "          Cache directory:   ${cache_dir}"
  _msg_info "          GNUPG directory:   ${gnupg_home}"
  _msg_info "  GNUPG private directory:   ${gnupg_private}"
  _msg_info "         Source publisher:   ${source_publisher}"
  _msg_info "           Target package:   ${target_package}"
  _msg_info "          Target revision:   ${target_revision}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2034
while \
  getopts \
    'A:V:B:C:ud:N:w:p:s:n:k:C:H:G:P:r:cvh?' \
    arg; do
  case \
    "${arg}" in
    A) override_up_address="${OPTARG}" ;;
    V) override_up_version="${OPTARG}" ;;
    u) override_user_level="y" ;;
    d) override_deployments_dir="${OPTARG}" ;;
    N) override_wallet_name="${OPTARG}" ;;
    w) override_wallet_path="${OPTARG}" ;;
    p) override_wallet_password="${OPTARG}" ;;
    s) override_wallet_seed="${OPTARG}" ;;
    n) override_target_network="${OPTARG}" ;;
    k) override_api_key="${OPTARG}" ;;
    C) override_cache_dir="${OPTARG}" ;;
    H) override_gnupg_home="${OPTARG}" ;;
    G) override_gnupg_private="${OPTARG}" ;;
    P) override_source_publisher="${OPTARG}" ;;
    r) override_target_revision="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _msg_error \
    "no package specified" \
    0
  _set_overrides
  _usage \
    1
fi
if (( 0 < $# )); then
  _set \
    "target" \
    "package" \
    "${1}"
fi
shift \
  1 || \
  true
command_args+=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${ur_address}"
  "${ur_version}"
  "${up_address}"
  "${up_version}"
  "${pp_address}"
  "${pp_version}"
  "${deployments_dir}"
  "${wallet_name}"
  "${wallet_path}"
  "${wallet_password}"
  "${wallet_seed}"
  "${target_network}"
  "${api_key}"
  "${cache_dir}"
  "${gnupg_home}"
  "${gnupg_private}"
  "${source_publisher}"
  "${target_package}"
  "${target_revision}"
)
_ur_package_info \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
